spring:
  datasource:
    hikari:
      driver-class-name: com.taosdata.jdbc.TSDBDriver
      jdbc-url: jdbc:TAOS://127.0.0.1:6030/sentinel_metric
      username: root
      password: taosdata
      connection-timeout: 10000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20

auth:
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png
  username: sentinel
  password: sentinel
server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    session:
      cookie:
        name: sentinel_dashboard_cookie
logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      taosdata:
        jdbc:
          springbootdemo:
            dao: DEBUG
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
sentinel:
  dashboard:
    version: @project.version@
