spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb
    username: sa
    password:
    druid:
      initial-size: 5
      min-idle: 5
      max-idle: 20
      max-active: 20
      max-wait: 60000
      validation-query: 'select server_status();'
      validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
  tdengine-Datasource:
    driver-class-name: com.taosdata.jdbc.TSDBDriver
    jdbc-url: jdbc:TAOS://${DB_URL:127.0.0.1}:6030/${DB_NAME:sentinel_metric}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:taosdata}
tdengine:
  enabled: ${TDENGINE_ENABLED:false}
auth:
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png
  username: ${SENTINEL_USERNAME:sentinel}
  password: ${SENTINEL_PASSWORD:sentinel}
server:
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
    session:
      cookie:
        name: sentinel_dashboard_cookie
logging:
  level:
    org:
      springframework:
        web: INFO
    com:
      taosdata:
        jdbc:
          springbootdemo:
            dao: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
sentinel:
  dashboard:
    version: @project.version@
